version: '3.8'

services:

  app:
    image: esjgroupinc/django-drf
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=mydb-dev
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
    ports:
      - "5431:5432"
    volumes:
      - tutorial-volume:/var/lib/postgresql/data

volumes:
  tutorial-volume: