---

- hosts: localhost

  tasks:

  - name: Stop the running container

    command: docker stop esj_backend_dev-fastapi_app-deployment_app_1

    ignore_errors: True



  - name: remove the running container

    command: docker rm esj_backend_dev-fastapi_app-deployment_app_1

    ignore_errors: True



  - name: remove the running image

    command: docker rmi esjgroupinc/django-drf:latest

    ignore_errors: True


  - name: Create and run docker-compose file

    command: docker-compose up -d --build